version: '3'
services:
  agent:
    image: "datadog/agent:6.2.1"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
    ports:
      - "8126:8126"
  redis:
    image: "redis:4.0.10-alpine"
  web:
    environment:
      - FLASK_APP=api.py
      - FLASK_DEBUG=1
    build: .
    command: flask run --port=5000 --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - "./step0${STEP}:/app"
    depends_on:
      - agent
      - redis
      - thinker
  thinker:
    environment:
    - FLASK_APP=thinker.py
    - FLASK_DEBUG=1
    build: .
    command: flask run --port=5001 --host=0.0.0.0
    ports:
      - "5001:5001"
    volumes:
      - "./step0${STEP}:/app"
    depends_on:
      - agent
      - redis
  humanherd:
    environment:
    - FLASK_APP=herd.py
    - FLASK_DEBUG=0
    build: .
    command: flask run --port=5002 --host=0.0.0.0
    ports:
      - "5001:5001"
    volumes:
      - "./step0${STEP}:/app"
    depends_on:
      - web