version: '3'
services:
  redis:
    image: "redis:4.0.10-alpine"
  web:
    image: "<yourrepositoryimagegoeshere>"
    environment:
      - FLASK_APP=api.py
    command: flask run --port=80 --host=0.0.0.0
    ports:
      - "80:80"
    depends_on:
      - agent
      - redis
      - thinker
  thinker:
    image: "<yourrepositoryimagegoeshere>"
    environment:
    - FLASK_APP=thinker.py
    command: flask run --port=5001 --host=0.0.0.0
    ports:
      - "5001:5001"
    depends_on:
      - agent
      - redis
